#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
PROBLEMS_DIR="${REPO_ROOT}/problems"

generate_ring_model() {
  local output_path="$1"
  local nodes="$2"
  local scale="$3"
  local max_index=$((nodes - 1))

  {
    echo "-- Generated by problems/generators/regenerate_p900_p905.sh"
    echo "-- Family: ring, scale: ${scale}, nodes: ${nodes}"
    echo "channel step : {0..${max_index}}"
    printf "Ring = "
    for ((i = 0; i < nodes; i++)); do
      printf "step.%d -> " "${i}"
    done
    echo "Ring"
    echo "assert Ring :[deadlock free [F]]"
  } >"${output_path}"
}

generate_philosophers_model() {
  local output_path="$1"
  local philosophers="$2"
  local scale="$3"
  local max_index=$((philosophers - 1))
  local system_expr="PHIL0"

  for ((i = 1; i < philosophers; i++)); do
    system_expr="(${system_expr} ||| PHIL${i})"
  done

  {
    echo "-- Generated by problems/generators/regenerate_p900_p905.sh"
    echo "-- Family: dining philosophers, scale: ${scale}, philosophers: ${philosophers}"
    echo "channel think, eat : {0..${max_index}}"
    for ((i = 0; i < philosophers; i++)); do
      echo "PHIL${i} = think.${i} -> eat.${i} -> PHIL${i}"
    done
    echo "System = ${system_expr}"
    echo "assert System :[deadlock free [F]]"
  } >"${output_path}"
}

generate_abp_model() {
  local output_path="$1"
  local max_value="$2"
  local scale="$3"

  {
    echo "-- Generated by problems/generators/regenerate_p900_p905.sh"
    echo "-- Family: alternating bit protocol, scale: ${scale}, sequence max: ${max_value}"
    echo "channel send, ack, out : {0..${max_value}}"
    printf "Sender = "
    for ((i = 0; i <= max_value; i++)); do
      printf "send!%d -> ack?%d -> " "${i}" "${i}"
    done
    echo "Sender"
    echo "Receiver = send?b -> out!b -> ack!b -> Receiver"
    echo "System = Sender [|{|send,ack|}|] Receiver"
    echo "assert System :[deadlock free [F]]"
  } >"${output_path}"
}

mkdir -p \
  "${PROBLEMS_DIR}/P900_ring_n_generator" \
  "${PROBLEMS_DIR}/P901_dining_philosophers_small" \
  "${PROBLEMS_DIR}/P902_abp_tiny" \
  "${PROBLEMS_DIR}/P903_ring_medium" \
  "${PROBLEMS_DIR}/P904_dining_philosophers_medium" \
  "${PROBLEMS_DIR}/P905_abp_medium"

generate_ring_model "${PROBLEMS_DIR}/P900_ring_n_generator/model.cspm" 4 "tiny"
generate_philosophers_model "${PROBLEMS_DIR}/P901_dining_philosophers_small/model.cspm" 3 "tiny"
generate_abp_model "${PROBLEMS_DIR}/P902_abp_tiny/model.cspm" 1 "tiny"

generate_ring_model "${PROBLEMS_DIR}/P903_ring_medium/model.cspm" 16 "medium"
generate_philosophers_model "${PROBLEMS_DIR}/P904_dining_philosophers_medium/model.cspm" 5 "medium"
generate_abp_model "${PROBLEMS_DIR}/P905_abp_medium/model.cspm" 3 "medium"

echo "Generated model.cspm for P900-P905."
